version: '2'
services:
  kafka-producer1:
    image: openexchange/kafka-producer:latest
    network_mode: "host"
    ports:
      - "8101:8101"
      - "9011:9011"
    environment:
      JAVA_OPTS: |
        ${JAVA_OPTS}
        -Dserver.port=8101
        -server
        -ea
        -Xms64m
        -Xmx128m
        -XX:MaxMetaspaceSize=64m
        -Xmn16m -XX:SurvivorRatio=8
        -XX:TargetSurvivorRatio=50
        -XX:+UseConcMarkSweepGC
        -XX:GCTimeRatio=19
        -XX:+CMSParallelRemarkEnabled
        -verbose:gc
        -XX:+PrintGCDetails
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9011
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.rmi.port=9011
    restart: always
  kafka-producer2:
    image: openexchange/kafka-producer:latest
    network_mode: "host"
    ports:
      - "8102:8102"
      - "9012:9012"
    environment:
      JAVA_OPTS: |
        ${JAVA_OPTS}
        -Dserver.port=8102
        -server
        -ea
        -Xms64m
        -Xmx128m
        -XX:MaxMetaspaceSize=64m
        -Xmn16m -XX:SurvivorRatio=8
        -XX:TargetSurvivorRatio=50
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:GCTimeRatio=19
        -verbose:gc
        -XX:+PrintGCDetails
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9012
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.rmi.port=9012
    restart: always
  kafka-producer3:
    image: openexchange/kafka-producer:latest
    network_mode: "host"
    ports:
      - "8103:8103"
      - "9013:9013"
    environment:
      JAVA_OPTS: |
        ${JAVA_OPTS}
        -Dserver.port=8103
        -server
        -ea
        -Xms64m
        -Xmx128m
        -XX:MaxMetaspaceSize=64m
        -Xmn16m -XX:SurvivorRatio=8
        -XX:TargetSurvivorRatio=50
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:GCTimeRatio=19
        -verbose:gc
        -XX:+PrintGCDetails
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9013
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.rmi.port=9013
    restart: always
  kafka-producer4:
    image: openexchange/kafka-producer:latest
    network_mode: "host"
    ports:
      - "8104:8104"
      - "9014:9014"
    environment:
      JAVA_OPTS: |
        ${JAVA_OPTS}
        -Dserver.port=8104
        -server
        -ea
        -Xms64m
        -Xmx128m
        -XX:MaxMetaspaceSize=64m
        -Xmn16m -XX:SurvivorRatio=8
        -XX:TargetSurvivorRatio=50
        -XX:+UseConcMarkSweepGC
        -XX:+CMSParallelRemarkEnabled
        -XX:GCTimeRatio=19
        -verbose:gc
        -XX:+PrintGCDetails
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9014
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.rmi.port=9014
    restart: always